### ISSUE TITLE
Caught Exception with every command

### ISSUE THREAD

**Issue by ghost** [lgladdy/SkyRemote#2]
When using any of the control commands, like this:

```
skyRemote> control getmediainfo
```

I always get the same error message saying:

```
Caught exception: 'Getmediainfo'
Are you sure you've specified the correct action?
Sent Getmediainfo command
```

This happens for any control, regardless of uppercase, lowercase, or combined as shown in the documentation.

Am I missing something here?

**Comment by lgladdy** [comment]
Sky have changed a lot since this project was released. You should look into using https://github.com/dalhundal/sky-plus-hd instead! :)
